name: my_flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^0.13.3
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  build_runner: ^2.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/heout_logo.png

